import api from './api'; const d = r => r.data; const B = '/student/connect';
export const getMe = () => api.get(`${B}/me`).then(d);
export const saveMe = b => api.put(`${B}/me`, b).then(d);
export const skillList = () => api.get(`${B}/skills`).then(d);
export const matches = skill => api.get(`${B}/matches`, { params: skill ? { skill } : {} }).then(d);
export const memberDetail = id => api.get(`${B}/members/${id}`).then(d);
export const feed = params => api.get(`${B}/feed`, { params }).then(d);
export const createPost = b => api.post(`${B}/posts`, b).then(d);
export const deletePost = id => api.delete(`${B}/posts/${id}`).then(d);
export const likePost = id => api.post(`${B}/posts/${id}/like`).then(d);
export const togglePost = id => api.post(`${B}/posts/${id}/status`).then(d);
export const commentPost = (id, text) => api.post(`${B}/posts/${id}/comments`, { text }).then(d);
export const connections = () => api.get(`${B}/connections`).then(d);
export const connect = toId => api.post(`${B}/connections`, { toId }).then(d);
export const acceptConn = id => api.post(`${B}/connections/${id}/accept`).then(d);
export const removeConn = id => api.delete(`${B}/connections/${id}`).then(d);
export const chats = () => api.get(`${B}/chats`).then(d);
export const messages = peerId => api.get(`${B}/chats/${peerId}/messages`).then(d);
export const sendMessage = (peerId, text) => api.post(`${B}/chats/${peerId}/messages`, { text }).then(d);
export const badges = () => api.get(`${B}/badges`).then(d);
export const errMsg = e => e?.response?.data?.message || e?.message || 'Something went wrong';
